CREATE DATABASE SQL_PROJECT;
USE SQL_PROJECT;


-- TABLE 1- SUPPLIER
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);
SELECT * FROM SUPPLIER;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

SELECT * FROM CATEGORIES;


-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

ALTER TABLE EMPLOYEES
RENAME COLUMN EMP_NAME TO NAME;
ALTER TABLE EMPLOYEES
RENAME COLUMN HIRE_DATE TO HIREDATE,
RENAME COLUMN EMP_ID TO EMPLOYEEID;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);
SELECT * FROM CUSTOMERS;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
SELECT * FROM PRODUCTS;
SHOW TABLES;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);


SELECT * FROM EMPLOYEES;

SHOW TABLES;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
SELECT * FROM ORDER_DETAILS;
SELECT * FROM ORDERS;

-- Analysis Questions
-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.
-- How many unique customers have placed orders?

show tables;
select count(distinct(cust_id)) as total_unique_cust from orders;

-- 2.Which customers have placed the highest number of orders?

select cust_name,count(*) as most_orders
from customers as t1
left join orders as t2
on t1.cust_id=t2.cust_id
group by cust_name
having most_orders>=4
order by most_orders desc ;

-- 3.What is the total and average purchase value per customer?

select t3.cust_name,sum(t1.total_price) as total_purchase,
avg(t1.total_price) as avg_purchase
from order_details as t1
join orders t2
on t1.ord_id = t2.ord_id
join customers t3
on t2.cust_id=t3.cust_id
group by t3.cust_name;

-- 4.Who are the top 5 customers by total purchase amount?

select t3.cust_name,sum(t1.total_price) as total_purchase
from order_details as t1
join orders t2
on t1.ord_id = t2.ord_id
join customers t3
on t2.cust_id=t3.cust_id
group by t3.cust_name
order by total_purchase desc
limit 5;



-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

-- 1.How many products exist in each category?

select cat_name,count(prod_name) as Total_Products from categories t1
join products t2
on t1.cat_id=t2.cat_id
group by t1.cat_name;


-- 2. What is the average price of products by category?

select cat_name,avg(price) as Average_price from categories t1
join products t2
on t1.cat_id=t2.cat_id
group by cat_name;


-- 3.Which products have the highest total sales volume (by quantity)?

select t2.prod_name,count(t1.prod_id) as quantity from order_details t1
left join products t2
on t1.prod_id=t2.prod_id
group by prod_name
order by quantity desc;


-- 4.What is the total revenue generated by each product?
select t2.prod_name,sum(total_price) Revenue from order_details t1
join products t2
on t1.prod_id=t2.prod_id
group by t2.prod_name;


-- 5.How do product sales vary by category and supplier



-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.


-- 1.How many orders have been placed in total?
select count(ord_id) total_orders 
from order_details;

-- 2.What is the average value per order?
select ord_id,avg(total_price) as average_value
from order_details
group by ord_id;


-- 3.On which dates were the most orders placed?
select order_date,count(ord_id) as total_orders from orders
group by order_date
order by total_orders desc;


-- 4.What are the monthly trends in order volume and revenue?

SELECT 
DATE_FORMAT(STR_TO_DATE(t3.order_date, '%m/%d/%Y'), '%Y-%m') AS month,
COUNT(t1.ord_id) AS total_orders,
sum(total_price) as Revenue from 
order_details t1
join products t2
on t1.prod_id=t2.prod_id
join orders t3
on t1.ord_id=t3.ord_id
GROUP BY DATE_FORMAT(STR_TO_DATE(t3.order_date, '%m/%d/%Y'), '%Y-%m')
ORDER BY month;

-- 5.How do order patterns vary across weekdays and weekends?

SELECT
    CASE 
        WHEN DAYOFWEEK(STR_TO_DATE(order_date, '%m/%d/%Y')) IN (1,7)
            THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
COUNT(DISTINCT t1.ord_id) AS total_orders,
SUM(t1.total_price) AS total_revenue
FROM order_details t1
JOIN orders t3
ON t1.ord_id = t3.ord_id
GROUP BY day_type;


-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- 1.How many suppliers are there in the database?
select count(sup_name) as total_suppliers
 from supplier;

-- 2.Which supplier provides the most products?
select t1.sup_name,count(prod_name) as total_products 
from supplier t1
join products t2
on t1.sup_id=t2.sup_id
group by sup_name
order by total_products desc
limit 1;

-- 3.What is the average price of products from each supplier?
select t1.sup_name,t2.prod_name,avg(price) as average_price
from supplier t1
join products t2
on t1.sup_id=t2.sup_id
group by sup_name,t2.prod_name;


-- 4.Which suppliers contribute the most to total product sales (by revenue)?
select t1.sup_name,sum(price) as revenue
from supplier t1
join products t2
on t1.sup_id=t2.sup_id
group by sup_name
order by revenue desc
limit 2;



-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.

-- 1.How many employees have processed orders?
select count(distinct(name)) as employees_count,
case 
when count(ord_id)>0 then "processed orders"
else "no orders"
end as order_status
from employees t1
left join orders t2
on t1.employeeid=t2.emp_id;

-- or
 
select t1.employeeid,name,count(ord_id) as total_orders,
case 
when count(ord_id)>0 then "processed orders"
else "no orders"
end as order_status
from employees t1
left join orders t2
on t1.employeeid=t2.emp_id
group by t1.employeeid,name;



-- 2.Which employees have handled the most orders?
select name,count(ord_id) as total_orders
from employees t1
join orders t2
on t1.employeeid=t2.emp_id
group by name
order by total_orders desc
limit 5;


-- 3.What is the total sales value processed by each employee?
select name,sum(t3.total_price) as total_sales_value
from employees t1
join orders t2
on t1.employeeid=t2.emp_id
join order_details t3
on t2.ord_id=t3.ord_id
group by name;

-- 4.What is the average order value handled per employee?

select name,avg(t3.total_price) as average_order_value
from employees t1
join orders t2
on t1.employeeid=t2.emp_id
join order_details t3
on t2.ord_id=t3.ord_id
group by name;


-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.

-- 1.What is the relationship between quantity ordered and total price?


-- 2.What is the average quantity ordered per product?
select prod_name,round(avg(quantity)) as avg_quantity
 from products t1
join order_details t2
on t1.prod_id=t2.prod_id
group by prod_name;

-- 3.How does the unit price vary across products and orders?
